FROM python:3.11-slim
WORKDIR /app
COPY python_script/app.py .
COPY python_script/generate_data.py .
COPY python_script/templates ./templates
RUN pip install --no-cache-dir flask
EXPOSE 8000
CMD ["python", "app.py"]
